In [43]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn.impute import KNNImputer
import matplotlib.pyplot as pl

In [124]:
# HDI
df_HDI = pd.read_csv('data/human-development-index-vs-gdp-per-capita.csv')
df_HDI.drop(columns=df_HDI.columns[-1], axis=1, inplace=True)


df_HDI = df_HDI[['Entity', 'Year', 'Human Development Index']]
df_HDI = df_HDI.pivot(index='Entity', columns='Year').reset_index()
df_HDI.columns = df_HDI.columns.get_level_values(1)
df_HDI = df_HDI.rename(columns={'':'Countries'})


l = [x for x in range(1990, 2022, 1)]
l = l.insert(0, 'Countries')


df_HDI[l]


# df_HDI.to_csv(r'C:\Users\pc\Desktop\countries\countries classifiers v2\countriesClassification\data\HDI.csv')
# df_HDI.drop(['Year'], axis=1)
# df_HDI = df_HDI.set_index('Year')
# df_HDI.groupby(by=['Year', 'Entity']).rank()
# df_HDI = df_HDI.T
# df_HDI
# l = df_HDI.columns.sort_values()
# df_HDI[l]

KeyError: None

In [ ]:
df_HDI.set_index(df_HDI['Year'])

,Entity,Code,Year,Human Development Index,"GDP per capita, PPP (constant 2017 international $)",Population (historical estimates)
Year,,,,,,
2015,Abkhazia,OWID_ABK,2015,NaN,NaN,NaN
1990,Afghanistan,AFG,1990,0.273,NaN,10694804.0
1991,Afghanistan,AFG,1991,0.279,NaN,10745168.0
1992,Afghanistan,AFG,1992,0.287,NaN,12057436.0
1993,Afghanistan,AFG,1993,0.297,NaN,14003764.0
...,...,...,...,...,...,...
1985,Zimbabwe,ZWE,1985,NaN,NaN,8690516.0
1986,Zimbabwe,ZWE,1986,NaN,NaN,8983048.0
1987,Zimbabwe,ZWE,1987,NaN,NaN,9277484.0
1988,Zimbabwe,ZWE,1988,NaN,NaN,9568745.0
1989,Zimbabwe,ZWE,1989,NaN,NaN,9846352.0